server {
    listen 80;
    server_name lagoinha-porto-camp.sevenfaithtech.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://lagoinha-porto-camp.sevenfaithtech.com$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lagoinha-porto-camp.sevenfaithtech.com;

    ssl_certificate     /etc/letsencrypt/live/lagoinha-porto-camp.sevenfaithtech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lagoinha-porto-camp.sevenfaithtech.com/privkey.pem;

    location / {
        proxy_pass http://lagoinha_porto_camp_web:80;

        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
        proxy_busy_buffers_size 32k;
        proxy_read_timeout 60s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
